### ISSUE TITLE
The "Process" item does not work

### ISSUE THREAD

**Issue by Rak1ta** [hakandundar34coding/system-monitoring-center#184]
After updating from v1.43.4 to v1.43.5, the process point does not work

```
OS: Raspbian GNU/Linux 10 (buster)
OS architecture: 32-bit
Kernel: armv7l 5.10.103-v7l+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.65 GB
Raspberry Pi OS image version: 2021-05-07
Language: en_US.UTF-8
```
![Безымянный](https://github.com/hakandundar34coding/system-monitoring-center/assets/88277343/ddf82196-0b10-483c-a0ba-b294da14e73d)

**Comment by hakandundar34coding** [comment]
Can you follow these steps?

- Run the applicaton by using the following command: `system-monitoring-center`
- Share the errors

**Comment by Rak1ta** [comment]
@hakandundar34coding 

```
pi@raspberrypi:~ $ system-monitoring-center
Traceback (most recent call last):
  File "/usr/share/system-monitoring-center/src/MainGUI.py", line 378, in on_main_gui_tab_radiobuttons_toggled
    self.main_gui_tab_switch_func()
  File "/usr/share/system-monitoring-center/src/MainGUI.py", line 584, in main_gui_tab_switch_func
    Processes.processes_loop_func()
  File "/usr/share/system-monitoring-center/src/Processes.py", line 410, in processes_loop_func
    reset_row_unique_data_list_prev = treeview_add_remove_columns(TabObject_data)
  File "/usr/share/system-monitoring-center/src/Processes.py", line 579, in treeview_add_remove_columns
    treemodelsort = Gtk.TreeModelSort().new_with_model(treemodelfilter)
AttributeError: 'TreeModelSort' object has no attribute 'new_with_model'
```

**Comment by hakandundar34coding** [comment]
Can you follow these steps?

- Open `src` folder in the installation directory of the application
- Open `Processes.py` file and go to line `579`
- Remove ```treemodelsort = Gtk.TreeModelSort().new_with_model(treemodelfilter)```
- Add ```treemodelsort = Gtk.TreeModelSort(treemodelfilter)``` (Note: there have to be 8 spaces at the beginning of the line)
- Save file and run the application by using the following command: ```system-monitoring-center```
- Open Processes tab
- Share command output

**Comment by Rak1ta** [comment]
@hakandundar34coding this option works
```
(system-monitoring-center:15300): Gtk-WARNING **: 11:11:37.272: Negative content height -8 (allocation 1, extents 4x5) while allocating gadget (node button, owner GtkButton)
```
![Безымянный](https://github.com/hakandundar34coding/system-monitoring-center/assets/88277343/b02adfea-d10d-4333-8022-fc0bea000f1e)

**Comment by Rak1ta** [comment]
> 4 spaces

4 or 8?

**Comment by hakandundar34coding** [comment]
Update: 8 spaces.
Previous comments is updated.

The warnings are printed because of GTK3 bug. They are not printed if GTK4 is used. The application will be updated today (v1.43.6).

**Comment by hakandundar34coding** [comment]
@theofficialgman, @Botspot,
There was a bug that prevented listing processes on Processes tab. It is fixed in v1.43.6 today. It looks like applications are usually updated on Pi-Apps on Wednesdays. But it has already been updated today. Can you update System Monitoring Center today?

**Comment by Rak1ta** [comment]
@hakandundar34coding should the update be here?
https://github.com/hakandundar34coding/system-monitoring-center/releases

**Comment by hakandundar34coding** [comment]
> @hakandundar34coding should the update be here?
https://github.com/hakandundar34coding/system-monitoring-center/releases

For the previous versions, packages could be listed  by using the link that you wrote. But it (v1.43.6) is not shown today.
You can view it by using the latest version link on the main page of the project.


![smc](https://github.com/hakandundar34coding/system-monitoring-center/assets/90193017/44c7ba6b-f203-4987-8831-40e18518679f)

**Comment by theofficialgman** [comment]
Running updater now (will be updated in 30mins-1hr)

**Comment by hakandundar34coding** [comment]
The bug is fixed and the application can be updated by using Pi-Apps. I will close this issue.
